"""initial_schema

Revision ID: f4faedc5e8bb
Revises: 
Create Date: 2026-07-22 15:53:57.511787
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4faedc5e8bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_category_stats')
    op.drop_index(op.f('idx_attempt_answers_telemetry'), table_name='attempt_answers')
    op.drop_column('books', 'pdf_url')
    op.drop_index(op.f('idx_mcqs_global_category'), table_name='mcqs', postgresql_where='(user_id IS NULL)')
    op.drop_index(op.f('idx_mcqs_main_category'), table_name='mcqs')
    op.drop_index(op.f('idx_mcqs_quiz_set_id'), table_name='mcqs')
    op.drop_index(op.f('idx_mcqs_sub_category'), table_name='mcqs')
    op.drop_index(op.f('idx_mcqs_user_category'), table_name='mcqs')
    op.drop_constraint(op.f('mcqs_user_id_fkey'), 'mcqs', type_='foreignkey')
    op.drop_column('mcqs', 'generation_type')
    op.drop_column('mcqs', 'user_id')
    op.alter_column('quiz_attempts', 'timer_mode',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'none'::text"))
    op.alter_column('quiz_attempts', 'feedback_mode',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'tutor'::text"))
    op.drop_index(op.f('idx_quiz_attempts_user_completed'), table_name='quiz_attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_quiz_attempts_user_completed'), 'quiz_attempts', ['user_id', 'completed_at'], unique=False)
    op.alter_column('quiz_attempts', 'feedback_mode',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'tutor'::text"))
    op.alter_column('quiz_attempts', 'timer_mode',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'none'::text"))
    op.add_column('mcqs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mcqs', sa.Column('generation_type', sa.TEXT(), server_default=sa.text("'static'::text"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('mcqs_user_id_fkey'), 'mcqs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_mcqs_user_category'), 'mcqs', ['user_id', 'main_category', 'sub_category'], unique=False)
    op.create_index(op.f('idx_mcqs_sub_category'), 'mcqs', ['sub_category'], unique=False)
    op.create_index(op.f('idx_mcqs_quiz_set_id'), 'mcqs', ['quiz_set_id'], unique=False)
    op.create_index(op.f('idx_mcqs_main_category'), 'mcqs', ['main_category'], unique=False)
    op.create_index(op.f('idx_mcqs_global_category'), 'mcqs', ['main_category', 'sub_category'], unique=False, postgresql_where='(user_id IS NULL)')
    op.add_column('books', sa.Column('pdf_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_attempt_answers_telemetry'), 'attempt_answers', ['quiz_attempt_id', 'mcq_id', 'is_correct'], unique=False)
    op.create_table('user_category_stats',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('main_category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sub_category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_category_stats_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'main_category', 'sub_category', name=op.f('user_category_stats_pkey'))
    )
    # ### end Alembic commands ###
